
#dict(bins=100, log=True, func="np.log10", range=[-10, 40] )
default_plots = {
'Alpha' : None,
'Alpha_Off_1' : None,
'Alpha_Off_2' : None,
'Alpha_Off_3' : None,
'Alpha_Off_4' : None,
'Alpha_Off_5' : None,
'AzPointing' : False,
'AzSourceCalc' : None,
'AzTracking' : False,
'COGx' : None,
'COGy' : None,
'ConcCore' : dict(bins=100, range=[0.0, 1.0], log=True, func=False, xUnit="a.u."),
'Concentration_onePixel' : dict(bins=100, range=[0.0, 1.0], log=True, func=False, xUnit="a.u."),
'Concentration_twoPixel' : dict(bins=100, range=[0.0, 1.0], log=True, func=False, xUnit="a.u."),
'CosDeltaAlpha' : dict(bins=100, range=[-1.5, 1.5], log=False, func=False, xUnit="a.u."),
'CosDeltaAlpha_Off_1' : dict(bins=100, range=[-1.5, 1.5], log=False, func=False, xUnit="a.u."),
'CosDeltaAlpha_Off_2' : dict(bins=100, range=[-1.5, 1.5], log=False, func=False, xUnit="a.u."),
'CosDeltaAlpha_Off_3' : dict(bins=100, range=[-1.5, 1.5], log=False, func=False, xUnit="a.u."),
'CosDeltaAlpha_Off_4' : dict(bins=100, range=[-1.5, 1.5], log=False, func=False, xUnit="a.u."),
'CosDeltaAlpha_Off_5' : dict(bins=100, range=[-1.5, 1.5], log=False, func=False, xUnit="a.u."),
'Delta' : None,
'Disp' : None,
'Distance' : dict(bins=100, range=[0.0, 300.0], log=True, func=False, xUnit="a.u." ),
'Distance_Off_1' : dict(bins=100, range=[0.0, 300.0], log=True, func=False, xUnit="a.u." ),
'Distance_Off_2' : dict(bins=100, range=[0.0, 300.0], log=True, func=False, xUnit="a.u." ),
'Distance_Off_3' : dict(bins=100, range=[0.0, 300.0], log=True, func=False, xUnit="a.u." ),
'Distance_Off_4' : dict(bins=100, range=[0.0, 300.0], log=True, func=False, xUnit="a.u." ),
'Distance_Off_5' : dict(bins=100, range=[0.0, 300.0], log=True, func=False, xUnit="a.u." ),
'EventNum' : dict(bins=100, range=[0.0, 15e4], log=True, func=False, xUnit="a.u." ),
'Leakage' : dict(bins=100, range=[0.0, 1.0], log=True, func=False, xUnit="a.u." ),
'Leakage2' : dict(bins=100, range=[0.0, 1.0], log=True, func=False, xUnit="a.u." ),
'Length' : dict(bins=100, range=[0.0, 80.0], log=True, func=False, xUnit="a.u." ),
'M3Long' : dict(bins=100, range=[-1.5, 1.5], log=False, func=False, xUnit="a.u." ),
'M3Trans' : dict(bins=100, range=[-1.5, 1.5], log=False, func=False, xUnit="a.u." ),
'M4Long' : dict(bins=100, range=[1, 5], log=False, func=False, xUnit="a.u." ),
'M4Trans' : dict(bins=100, range=[1, 5], log=False, func=False, xUnit="a.u." ),
'NPIX' : False,
'NROI' : False,
'Size' : dict(bins=150, range=[1.0, 5.3], log=True, func="np.log10", xUnit="p.e." ),
'Slope_long' : dict(bins=100, range=[-1, 1], log=False, func=False, xUnit="a.u." ),
'Slope_spread' : dict(bins=100, range=[0, 10], log=False, func=False, xUnit="a.u." ),
'Slope_spread_weighted' : dict(bins=100, range=[0, 10], log=False, func=False, xUnit="a.u." ),
'Slope_trans' : dict(bins=100, range=[-0.6, 0.6], log=False, func=False, xUnit="a.u." ),
'Theta' : dict(bins=100, range=[0, 300], log=False, func=False, xUnit="a.u." ),
'Theta_Off_1' : dict(bins=100, range=[0, 300], log=False, func=False, xUnit="a.u." ),
'Theta_Off_2' : dict(bins=100, range=[0, 300], log=False, func=False, xUnit="a.u." ),
'Theta_Off_3' : dict(bins=100, range=[0, 300], log=False, func=False, xUnit="a.u." ),
'Theta_Off_4' : dict(bins=100, range=[0, 300], log=False, func=False, xUnit="a.u." ),
'Theta_Off_5' : dict(bins=100, range=[0, 300], log=False, func=False, xUnit="a.u." ),
'Timespread' : dict(bins=100, range=[0, 20], log=True, func=False, xUnit="a.u." ),
'Timespread_weighted' : dict(bins=100, range=[0, 20], log=True, func=False, xUnit="a.u." ),
'Width' : dict(bins=150, range=[0, 100], log=True, func=False, xUnit="mm" ),
'ZdPointing' : dict(bins=30, range=[0, 32], log=False, func=False, xUnit="deg" ),
'ZdSourceCalc' : dict(bins=30, range=[0, 32], log=False, func=False, xUnit="deg" ),
'ZdTracking' : dict(bins=30, range=[0, 32], log=False, func=False, xUnit="deg" ),
'arrTimePedestal_kurtosis' : dict(bins=80, range=[90, 103], log=True, func=False, xUnit="a.u." ),
'arrTimePedestal_max' : dict(bins=80, range=[90, 103], log=False, func=False, xUnit="a.u." ),
'arrTimePedestal_mean' : dict(bins=80, range=[45, 60], log=False, func=False, xUnit="a.u." ),
'arrTimePedestal_median' : dict(bins=80, range=[35, 65], log=False, func=False, xUnit="a.u." ),
'arrTimePedestal_min' : dict(bins=80, range=[0, 10], log=False, func=False, xUnit="a.u." ),
'arrTimePedestal_p25' : dict(bins=80, range=[20, 45], log=False, func=False, xUnit="a.u." ),
'arrTimePedestal_p75' : dict(bins=80, range=[60, 80], log=False, func=False, xUnit="a.u." ),
'arrTimePedestal_skewness' : dict(bins=100, range=[-0.4, 1.0], log=False, func=False, xUnit="a.u." ),
'arrTimePedestal_variance' : dict(bins=100, range=[400, 700], log=False, func=False, xUnit="a.u." ),
'arrTimePosShower_max' : dict(bins=70, range=[30, 100], log=False, func=False, xUnit="a.u." ),
'arrTimePosShower_mean' : dict(bins=50, range=[30, 80], log=False, func=False, xUnit="a.u." ),
'arrTimePosShower_min' : dict(bins=40, range=[25, 65], log=False, func=False, xUnit="a.u." ),
'arrTimePosShower_skewness' : None,
'arrTimePosShower_variance' : dict(bins=100, range=[-10, 400], log=True, func=False, xUnit="a.u." ),
'arrTimeShower_kurtosis' : dict(bins=100, range=[-10, 30], log=False, func=False, xUnit="a.u." ),
'arrTimeShower_max' : dict(bins=100, range=[10, 120], log=False, func=False, xUnit="a.u." ),
'arrTimeShower_mean' : dict(bins=100, range=[30, 90], log=False, func=False, xUnit="a.u." ),
'arrTimeShower_min' : dict(bins=100, range=[30, 70], log=False, func=False, xUnit="a.u." ),
'arrTimeShower_skewness' : dict(bins=100, range=[-5, 5], log=False, func=False, xUnit="a.u." ),
'arrTimeShower_variance' : dict(bins=100, range=[-10, 250], log=True, func=False, xUnit="a.u." ),
'arrivalTimeMean' : dict(bins=100, range=[40, 60], log=False, func=False, xUnit="a.u." ),
'concCOG' : None,
'm3l' : dict(bins=100, range=[-400, 400], log=True, func=False, xUnit="a.u." ),
'm3t' : dict(bins=100, range=[-400, 400], log=True, func=False, xUnit="a.u." ),
'maxPosShower_kurtosis' : None,
'maxPosShower_max' : dict(bins=60, range=[40, 100], log=False, func=False, xUnit="a.u." ),
'maxPosShower_mean' : dict(bins=60, range=[40, 100], log=False, func=False, xUnit="a.u." ),
'maxPosShower_min' : dict(bins=50, range=[30, 80], log=False, func=False, xUnit="a.u." ),
'maxPosShower_skewness' : None,
'maxPosShower_variance' : dict(bins=100, range=[-10, 300], log=True, func=False, xUnit="a.u." ),
'maxSlopesPedestal_kurtosis' : None,
'maxSlopesPedestal_max' : dict(bins=100, range=[0, 25], log=False, func=False, xUnit="a.u." ),
'maxSlopesPedestal_mean' : dict(bins=100, range=[1, 2.5], log=False, func=False, xUnit="a.u." ),
'maxSlopesPedestal_median' : dict(bins=100, range=[1, 2.5], log=False, func=False, xUnit="a.u." ),
'maxSlopesPedestal_min' : dict(bins=100, range=[-10, 0], log=False, func=False, xUnit="a.u." ),
'maxSlopesPedestal_p25' : dict(bins=100, range=[0, 2], log=False, func=False, xUnit="a.u." ),
'maxSlopesPedestal_p75' : dict(bins=100, range=[1, 3], log=False, func=False, xUnit="a.u." ),
'maxSlopesPedestal_skewness' : None,
'maxSlopesPedestal_variance' : dict(bins=100, range=[0, 3], log=False, func=False, xUnit="a.u." ),
'maxSlopesPosShower_kurtosis' : dict(bins=100, range=[-10, 20], log=False, func=False, xUnit="a.u." ),
'maxSlopesPosShower_max' : dict(bins=100, range=[0, 800], log=True, func=False, xUnit="a.u." ),
'maxSlopesPosShower_mean' : dict(bins=100, range=[0, 200], log=True, func=False, xUnit="a.u." ),
'maxSlopesPosShower_min' : dict(bins=40, range=[0, 40], log=False, func=False, xUnit="a.u." ),
'maxSlopesPosShower_skewness' : dict(bins=100, range=[-3, 5], log=False, func=False, xUnit="a.u." ),
'maxSlopesPosShower_variance' : dict(bins=100, range=[0, 0.5], log=True, func=False, xUnit="a.u." ),
'maxSlopesShower_kurtosis' : dict(bins=100, range=[-5, 20], log=False, func=False, xUnit="a.u." ),
'maxSlopesShower_max' : dict(bins=100, range=[0, 300], log=True, func=False, xUnit="a.u." ),
'maxSlopesShower_mean' : dict(bins=100, range=[0, 300], log=True, func=False, xUnit="a.u." ),
'maxSlopesShower_min' : dict(bins=100, range=[-10, 20], log=True, func=False, xUnit="a.u." ),
'maxSlopesShower_skewness' : dict(bins=100, range=[-3, 5], log=False, func=False, xUnit="a.u." ),
'maxSlopesShower_variance' : dict(bins=100, range=[-10, 200], log=True, func=False, xUnit="a.u." ),
'numIslands' : dict(bins=10, range=[0, 12], log=True, func=False, xUnit="a.u." ),
'numPixelInPedestal' : dict(bins=720, range=[0, 1440], log=True, func=False, xUnit="a.u." ),
'numPixelInShower' : dict(bins=720, range=[0, 1440], log=True, func=False, xUnit="a.u." ),
'ped_mean_kurtosis' : None,
'ped_mean_max' : dict(bins=100, range=[0, 4000], log=True, func=False, xUnit="a.u." ),
'ped_mean_mean' : dict(bins=100, range=[-1000, 1000], log=True, func=False, xUnit="a.u." ),
'ped_mean_median' : dict(bins=100, range=[-5000, 5000], log=True, func=False, xUnit="a.u." ),
'ped_mean_min' : dict(bins=100, range=[-2500, 1000], log=True, func=False, xUnit="a.u." ),
'ped_mean_p25' : dict(bins=100, range=[-500, 1000], log=True, func=False, xUnit="a.u." ),
'ped_mean_p75' : dict(bins=100, range=[-500, 1000], log=True, func=False, xUnit="a.u." ),
'ped_mean_skewness' : None,
'ped_mean_variance' : dict(bins=100, range=[0, 0.2], log=True, func=False, xUnit="a.u." ),
'ped_median_kurtosis' : None,
'ped_median_max' : dict(bins=100, range=[-10, 1200], log=False, func=False, xUnit="a.u." ),
'ped_median_mean' : dict(bins=100, range=[-500, 0], log=False, func=False, xUnit="a.u." ),
'ped_median_median' : dict(bins=100, range=[-500, 0], log=False, func=False, xUnit="a.u." ),
'ped_median_min' : dict(bins=100, range=[-2500, 0], log=False, func=False, xUnit="a.u." ),
'ped_median_p25' : dict(bins=100, range=[-500, 0], log=False, func=False, xUnit="a.u." ),
'ped_median_p75' : dict(bins=100, range=[-500, 0], log=False, func=False, xUnit="a.u." ),
'ped_median_skewness' : None,
'ped_median_variance' : dict(bins=100, range=[0, 1e5], log=False, func=False, xUnit="a.u." ),
'ped_std_kurtosis' : None,
'ped_std_max' : dict(bins=100, range=[0, 4000], log=True, func=False, xUnit="a.u." ),
'ped_std_mean' : dict(bins=100, range=[0, 3000], log=True, func=False, xUnit="a.u." ),
'ped_std_median' : dict(bins=100, range=[100, 800], log=True, func=False, xUnit="a.u." ),
'ped_std_min' : dict(bins=100, range=[-10, 500], log=True, func=False, xUnit="a.u." ),
'ped_std_p25' : dict(bins=100, range=[0, 500], log=True, func=False, xUnit="a.u." ),
'ped_std_p75' : dict(bins=100, range=[150, 500], log=True, func=False, xUnit="a.u." ),
'ped_std_skewness' : None,
'ped_std_variance' : dict(bins=100, range=[0, 0.02], log=True, func=False, xUnit="a.u." ),
'ped_sum_kurtosis' : None,
'ped_sum_max' : dict(bins=100, range=[0, 1e5], log=True, func=False, xUnit="a.u." ),
'ped_sum_mean' : dict(bins=100, range=[-5000, 5000], log=True, func=False, xUnit="a.u." ),
'ped_sum_median' : None,
'ped_sum_min' : None,
'ped_sum_p25' : None,
'ped_sum_p75' : None,
'ped_sum_skewness' : None,
'ped_sum_variance' : None,
'ped_var_kurtosis' : None,
'ped_var_max' : dict(bins=100, range=[0, 1], log=False, func=False, xUnit="a.u." ),
'ped_var_mean' : dict(bins=100, range=[0, 0.2], log=False, func=False, xUnit="a.u." ),
'ped_var_median' : dict(bins=100, range=[0, 0.2], log=False, func=False, xUnit="a.u." ),
'ped_var_min' : dict(bins=100, range=[0, 0.2], log=False, func=False, xUnit="a.u." ),
'ped_var_p25' : dict(bins=100, range=[0, 0.2], log=False, func=False, xUnit="a.u." ),
'ped_var_p75' : dict(bins=100, range=[0, 0.2], log=False, func=False, xUnit="a.u." ),
'ped_var_skewness' : dict(bins=100, range=[0, 0.1], log=False, func=False, xUnit="a.u." ),
'ped_var_variance' : dict(bins=100, range=[0, 0.1], log=False, func=False, xUnit="a.u." ),
'pedestalSize' : dict(bins=100, range=[-100, 2500], log=False, func=False, xUnit="a.u." ),
'pedestalTimespread' : dict(bins=100, range=[20, 28], log=False, func=False, xUnit="a.u." ),
'phChargePedestal_kurtosis' : None,
'phChargePedestal_max' : dict(bins=100, range=[0, 50], log=False, func=False, xUnit="a.u." ),
'phChargePedestal_mean' : dict(bins=100, range=[-1, 5], log=True, func=False, xUnit="a.u." ),
'phChargePedestal_median' : dict(bins=100, range=[-1, 5], log=True, func=False, xUnit="a.u." ),
'phChargePedestal_min' : dict(bins=100, range=[-10, 0], log=True, func=False, xUnit="a.u." ),
'phChargePedestal_p25' : dict(bins=100, range=[-3, 2], log=False, func=False, xUnit="a.u." ),
'phChargePedestal_p75' : dict(bins=100, range=[0, 5], log=False, func=False, xUnit="a.u." ),
'phChargePedestal_skewness' : None,
'phChargePedestal_variance' : dict(bins=100, range=[1, 5], log=False, func=False, xUnit="a.u." ),
'phChargeShower_kurtosis' : dict(bins=100, range=[-5, 20], log=False, func=False, xUnit="a.u." ),
'phChargeShower_max' : dict(bins=100, range=[0, 300], log=True, func=False, xUnit="a.u." ),
'phChargeShower_mean' : dict(bins=100, range=[0, 100], log=True, func=False, xUnit="a.u." ),
'phChargeShower_min' : dict(bins=100, range=[0, 20], log=True, func=False, xUnit="a.u." ),
'phChargeShower_skewness' : dict(bins=100, range=[-3, 5], log=False, func=False, xUnit="a.u." ),
'phChargeShower_variance' : dict(bins=100, range=[-10, 300], log=False, func=False, xUnit="a.u." ),
'photonchargeMean' : dict(bins=100, range=[0, 50], log=False, func=False, xUnit="a.u." ),
'sourcePosition' : False,
'timeGradientIntercept' : False,
'timeGradientIntercept_err' : False,
'timeGradientSSE' : False,
'timeGradientSlope' : False,
'timeGradientSlope_err' : False,
'TriggerType': False,
}
